### ISSUE TITLE
License

### ISSUE THREAD

**Issue by timthelion** [bryanjenningz/record-audio#1]
There is no license file. Could you please choose an open source license and add a license file?

**Comment by timthelion** [comment]
I used it in this microproject, the sound mirror, which I created as a toy for a local baby...

https://ipfs.io/ipfs/QmcV8JrsTg9XZ8EZjb2HjYSWKkTVxaNGakZchJ3kyLovZb/zrcadlo.html

Hope you don't mind...

**Comment by bryanjenningz** [comment]
You can use the code and do whatever you want with it. I just added an MIT license to this repo. Thanks!
