### ISSUE TITLE
doesn't work with safari

### ISSUE THREAD

**Issue by eeepad86** [bryanjenningz/record-audio#10]
it doesn't seem to work with safari, is it my problem? I think it is due to the mediastream

**Comment by bryanjenningz** [comment]
Thanks for adding this issue. If you add a MediaRecorder polyfill, such as this one https://github.com/ai/audio-recorder-polyfill, does that fix the problem?

**Comment by rus-yurchenko** [comment]
You need to specify the audio format to run in Safari. The following would work for every browser: 
`new Blob(audioChunks, { type: 'audio/mpeg' });`

**Comment by bryanjenningz** [comment]
Thanks @rus-yurchenko for the fix! I've added this change so it should be fixed now. Feel free to open this issue again if you still have this issue with the new code.
