### ISSUE TITLE
there should be a way to download the audio as mp3 or wav to export it to another application

### ISSUE THREAD

**Issue by Shaxadhere** [bryanjenningz/record-audio#11]

**Comment by bryanjenningz** [comment]
If you run the server example (https://github.com/bryanjenningz/record-audio/tree/master/record-server-example), you should be able to record and download audio. Once you have the audio file, you should be able to use it however you want. Is this what you mean?

**Comment by Shaxadhere** [comment]
got you. i sort it out anyways. thanks.

**Comment by JDuggal760** [comment]
How did you end up doing it without the server is their code that can save it to the file

**Comment by Shaxadhere** [comment]
yes i convert the file to mp3 and save it
