### ISSUE TITLE
where do i start?

### ISSUE THREAD

**Issue by BOW789** [bryanjenningz/record-audio#12]
give total step my friend

**Comment by bryanjenningz** [comment]
If you want to record audio locally without a server, then you can download this repo and open up the index.html file locally in your browser, then record audio and play the recorded audio locally in your browser.

If you want to be able to record and store audio on a server, you'll need to have Node.js installed and you'll need to go into the directory that has the server example and follow the instructions for how to run it: https://github.com/bryanjenningz/record-audio/tree/master/record-server-example

These examples can be used as a starting point. From there, you can use these examples to build a more complicated application if you want.
