### ISSUE TITLE
how can we save the audio blob into a folder?

### ISSUE THREAD

**Issue by BernardoOlisan** [bryanjenningz/record-audio#13]

**Comment by bryanjenningz** [comment]
Hi Bernardo, how are you?

The audio blob can be saved if you run the server example here: https://github.com/bryanjenningz/record-audio/tree/master/record-server-example

If you want to choose a specific folder, you'll have to change your download folder by going into your browser's settings.

There's also a new API for allowing users to choose which folder they want to download files to, but it's not stabilized yet and only works in Chrome, Edge, and Opera (https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker).

Let me know if you still have any questions about how to run the server example or if you have other questions.

**Comment by bryanjenningz** [comment]
I'm going to close this issue since it's not active but feel free to re-open it or comment if you still have any questions.
