### ISSUE TITLE
Uploading audio while it's still recording

### ISSUE THREAD

**Issue by OptimisticLock** [bryanjenningz/record-audio#14]
Hi,

I wonder how I could begin uploading the data while it's still recording? I suppose I'd need to record in small chunks like this:

`mediaRecorder.start(1000); // milliseconds per recorded chunk`

and then upload on 'dataavailable'.  

The header won't be fully formed until it's finished recording, but perhaps I can account for that on nodejs. Or just live without it, given that I am feeding audio files into ffmpeg on the backend anyway. Any suggestions?

**Comment by bryanjenningz** [comment]
I would try the technique that you mentioned where you send data on dataavailable events then you can combine those either on the server or you can stream those to a separate client.

Let me know if you have any issues.
