### ISSUE TITLE
upload recording to server

### ISSUE THREAD

**Issue by drogit** [bryanjenningz/record-audio#4]
dont suppose you have any nore of that fancy code that can then save/upload wav/mp3 to the server eh?  newbie dumbfounded as to how to convert that url into a useable link to upload the recording.
anyway, nice code dude, works great

**Comment by aschuss** [comment]
I am having same problem: Was trying something like:
// lines to send audio.audioBlob to messages post in Flask ... but need to convert audio.audioBlob to a wav file
// https://stackoverflow.com/questions/39875668/sending-audio-data-from-js-to-python/39879185
// something like blob = new Blob(something, {'type': 'audio/wav;'});
blob = new Blob([audio.audioBlob], {type: 'audio/wav;'}); 
fetch("/messages", {
  method: "post",
  body: blob
});
}

where /messages is in flask app:
@app.route('/messages', methods = ['POST'])
def api_message():
    f = open('./file.wav', 'wb')
    f.write(request.data)
    f.close()

however, it doesn't work.  Not converting it into a usable wav file....

Thanks.

**Comment by danleyb2** [comment]
what worked for me was setting the content type header in the http request
```js
var storageRef = window.firebase.storage().ref();
      var recordingRef = storageRef.child('recording'+new Date().getTime()+'.wav');
      // Create file metadata including the content type
      var metadata = {
        contentType: 'audio/wav',
      };
      recordingRef.put(audio.audioBlob,metadata).then(function(snapshot) {
        console.log('Uploaded recording succefully!');
      });
```
> uploading to firebase cloud storage

**Comment by bryanjenningz** [comment]
I added a simple example that shows how to have the user record audio and upload it and save it as a file on the server. https://github.com/bryanjenningz/record-audio/tree/master/record-server-example
