### ISSUE TITLE
Cannot Read Property of getUserMedia , play ,stop, audioblob.

### ISSUE THREAD

**Issue by oyusufa** [bryanjenningz/record-audio#7]
Hi,
When I try to run example server, it gives the error in the title. Can you help me?

**Comment by bryanjenningz** [comment]
Thanks for adding this issue. What does the error say?

**Comment by ghost** [comment]
Hi . I copied index.html and I ran it with laravel framework.The record , play and stop works correctly but I can not save it.
It returns me this when I press on save :
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Kishore-Dev-bit** [comment]
save is not working

**Comment by bryanjenningz** [comment]
Thanks for reporting this.

I'm wondering if you can give me steps for how to reproduce this issue so I can fix it for you. Thanks!
