### ISSUE TITLE
Increase the length of audio able to be saved

### ISSUE THREAD

**Issue by islalobo** [bryanjenningz/record-audio#9]
Hello!

I'm playing with your example, but want to save audio for longer than 3 seconds. I am not calling the sleep function. Is there something that will prevent more than 3 seconds of audio to be recorded or saved?

**Comment by bryanjenningz** [comment]
Hi!

You should be able to save audio for as long as you want. 

Here's an example of how you can get that set up: https://github.com/bryanjenningz/record-audio/tree/master/record-server-example

In this example, a person can continue recording audio until they want to stop recording by clicking a "Stop" button.

Let me know if you have any other questions.
